import AppDomain
import Core
import Domain
import FP
import Foundation
import SwiftRexArchitecture
import SwiftUI

// MARK: - HomeModule (public namespace — non-generic so @Lenses / @Prisms can expand)

/// Public-facing types for the Home feature.
///
/// Intentionally NOT nested inside the generic `Module<…>` — Swift prohibits
/// static stored properties (generated by `@Lenses` / `@Prisms`) inside generic types.
/// `Module.Home` is a typealias that makes the `Module.Home.*` dot-path work from the
/// outside without exposing the concrete `HomeModule` name everywhere.
public enum HomeModule {

    // MARK: - State

    @Lenses
    public struct State: Sendable {
        /// The canonical list of saved biokinetic models.
        public var documents: Loading<[ModelDocument], DecodingError> = .idle
        /// Tracks the file-picker lifecycle.
        /// `.loading` → picker sheet visible; `.loaded(())` → file chosen, importing;
        /// `.idle` → closed.
        public var filePicker: Loading<Terminal, Never> = .idle

        public init() {}
    }

    // MARK: - Action

    @Prisms @dynamicMemberLookup
    public enum Action: Sendable {
        // File picker state machine
        case openFilePicker
        case filePickerDismissed
        // Document management
        case newDocument
        case importXML(Data)
        case importResult(Result<ModelDocument, DecodingError>)
        case saveDocument(ModelDocument)
        case deleteDocument(ModelDocument.ID)
        case edit(document: ModelDocument)
        case calculate(document: ModelDocument)
    }

    // MARK: - Environment

    public struct Environment: Sendable {
        public var xmlDecoder: DataDecoderFactory & Sendable
        public init(xmlDecoder: DataDecoderFactory & Sendable) {
            self.xmlDecoder = xmlDecoder
        }
    }

    // MARK: - Content

    /// Public type-erasing view. The concrete `HomeView` (internal) is sealed inside;
    /// callers only see `Content: View`. Created exclusively within this module via
    /// the internal `init(_:)`.
    public struct Content: View {
        private let _body: AnyView

        /// Internal: only `Module.home` can vend a `Content` value.
        init(_ body: some View) {
            _body = AnyView(body)
        }

        public var body: some View { _body }
    }
}

// MARK: - Module.Home bridge

public extension Module {
    /// Makes `Module.Home.*` a valid dot-path for the public Home types.
    typealias Home = HomeModule
}

// MARK: - Module.home factory

public extension Module
where Action == HomeModule.Action,
      State  == HomeModule.State,
      Environment == HomeModule.Environment,
      Content == HomeModule.Content {

    static var home: Self {
        Module(
            behavior: HomeFeature.behavior(),
            view: { @MainActor store in
                let vm = HomeFeature.ViewModel(store: store.projection(
                    action: HomeFeature.mapAction,
                    state:  HomeFeature.mapState
                ))
                return HomeModule.Content(HomeFeature.Content(viewModel: vm))
            }
        )
    }
}
