import AppDomain
import Core
import Domain
import FP
import Foundation
import SwiftRexArchitecture
import SwiftUI

// MARK: - HomeModule (public namespace — non-generic so @Lenses / @Prisms can expand)

/// Public-facing types for the Home feature.
///
/// Intentionally NOT nested inside the generic `Module<…>` — Swift prohibits
/// static stored properties (generated by `@Lenses` / `@Prisms`) inside generic types.
/// `Module.Home` is a typealias that makes the `Module.Home.*` dot-path work from the
/// outside without exposing the concrete `HomeModule` name everywhere.
public enum HomeModule {

    // MARK: - State

    @Lenses
    public struct State: Sendable, Equatable {
        /// The canonical list of saved biokinetic models.
        public var documents: Loading<[ModelDocument], DecodingError> = .idle
        /// Tracks the file-picker lifecycle.
        public var filePicker: Loading<Terminal, Never> = .idle
        /// Whether the new-document creation sheet is presented.
        public var isCreationSheetOpen: Bool = false
        /// Draft field selection in the creation sheet.
        public var draftField: ModelField = .generic
        /// Draft name in the creation sheet.
        public var draftName: String = ""

        public init() {}
    }

    // MARK: - Action

    @Prisms @dynamicMemberLookup
    public enum Action: Sendable {
        // File picker state machine
        case openFilePicker
        case filePickerDismissed
        // Creation sheet
        case openCreationSheet
        case dismissCreationSheet
        case setDraftField(ModelField)
        case setDraftName(String)
        // Document management
        case loadDocuments
        case loadResult(Result<[ModelDocument], PersistenceError>)
        case newDocument(field: ModelField, name: String)
        case newDocumentReady(ModelDocument)
        case insertDocument(ModelDocument)
        case seedsReady([ModelDocument])
        case importXML(Data)
        case importJSON(Data)
        case importCSV(Data)
        case importResult(Result<ModelDocument, DecodingError>)
        case saveDocument(ModelDocument)
        case duplicateDocument(ModelDocument.ID)
        case deleteDocument(ModelDocument.ID)
        case edit(document: ModelDocument)
        case calculate(document: ModelDocument)
    }

    // MARK: - Environment

    public struct Environment: Sendable {
        public var xmlDecoder:        DataDecoderFactory & Sendable
        public var jsonDecoder:       DataDecoderFactory & Sendable
        public var newId:             @Sendable () -> UUID
        public var seedId:            @Sendable (String) -> UUID
        public var saveDocument:      @Sendable (ModelDocument) -> Result<Void, PersistenceError>
        public var loadAllDocuments:  @Sendable () -> Result<[ModelDocument], PersistenceError>
        public var deleteDocument:    @Sendable (UUID) -> Result<Void, PersistenceError>

        public init(
            xmlDecoder:       DataDecoderFactory & Sendable,
            jsonDecoder:      DataDecoderFactory & Sendable,
            newId:            @escaping @Sendable () -> UUID                                         = { UUID() },
            seedId:           @escaping @Sendable (String) -> UUID                                  = { _ in UUID() },
            saveDocument:     @escaping @Sendable (ModelDocument) -> Result<Void, PersistenceError>  = { _ in .success(()) },
            loadAllDocuments: @escaping @Sendable () -> Result<[ModelDocument], PersistenceError>    = { .success([]) },
            deleteDocument:   @escaping @Sendable (UUID) -> Result<Void, PersistenceError>           = { _ in .success(()) }
        ) {
            self.xmlDecoder       = xmlDecoder
            self.jsonDecoder      = jsonDecoder
            self.newId            = newId
            self.seedId           = seedId
            self.saveDocument     = saveDocument
            self.loadAllDocuments = loadAllDocuments
            self.deleteDocument   = deleteDocument
        }
    }

}

// MARK: - Module.Home bridge

public extension Module {
    /// Makes `Module.Home.*` a valid dot-path for the public Home types.
    typealias Home = HomeModule
}

// MARK: - Module.home factory

public extension Module
where Action == HomeModule.Action,
      State  == HomeModule.State,
      Environment == HomeModule.Environment,
      Content == HomeView {

    static var home: Self { .init(HomeFeature.self) }
}
