import XCTest
import Domain
import Solver

/// Validates the Swift Birchall solver against the C# "Validacao" reference model
/// (the 3-compartment test model bundled in the original SSID app).
///
/// Model topology:
///   A --0.1--> B <--0.05-- C
///              B ---0.2--> C
///
/// Intake: A = 1.0 (fraction).
/// Reference rows were generated by `ipen-validator` (the fixed C# port):
///   dotnet run -- --xml Validation.xml --intake 1 --fraction 1 --half-life <HL>
///                 --step 1 --final 50
final class ValidationModelTests: XCTestCase {

    // MARK: - Model factory

    private func makeModel(halfLife: Double) -> CompartmentalModel {
        let nuclide = Nuclide(id: "n0", name: "Validation", halfLife: halfLife)
        return CompartmentalModel(
            nuclides: [nuclide],
            compartments: [
                Compartment(id: "1", nuclideId: "n0", name: "A",
                            follow: true,  intake: true,  dispose: false, fraction: 1.0),
                Compartment(id: "2", nuclideId: "n0", name: "B",
                            follow: true,  intake: false, dispose: false, fraction: 0),
                Compartment(id: "3", nuclideId: "n0", name: "C",
                            follow: true,  intake: false, dispose: false, fraction: 0)
            ],
            connections: [
                CompartmentConnection(from: "1", to: "2", rate: 0.1),   // A → B
                CompartmentConnection(from: "2", to: "3", rate: 0.2),   // B → C
                CompartmentConnection(from: "3", to: "2", rate: 0.05)   // C → B
            ]
        )
    }

    private func run(halfLife: Double) async -> [[Double]] {
        await solve(
            plan: BiokineticsSimulationPlan(step: 1, final: 50, solver: .birchall(composition: .perTime)),
            model: makeModel(halfLife: halfLife)
        ).run()
    }

    // MARK: - half-life = 0 (stable substance)

    /// Key rows from the ipen-validator with --half-life 0.
    /// Index order is [A, B, C] == compartment order in the model.
    func testHalfLifeZero() async {
        let rows = await run(halfLife: 0)
        let eps = 1e-5

        // t=0
        XCTAssertEqual(rows[0][0], 1.0,          accuracy: eps, "A@t=0")
        XCTAssertEqual(rows[0][1], 0.0,          accuracy: eps, "B@t=0")
        XCTAssertEqual(rows[0][2], 0.0,          accuracy: eps, "C@t=0")

        // t=1
        XCTAssertEqual(rows[1][0], 9.048374e-01, accuracy: eps, "A@t=1")
        XCTAssertEqual(rows[1][1], 8.625206e-02, accuracy: eps, "B@t=1")
        XCTAssertEqual(rows[1][2], 8.910527e-03, accuracy: eps, "C@t=1")

        // t=5
        XCTAssertEqual(rows[5][0], 6.065307e-01, accuracy: eps, "A@t=5")
        XCTAssertEqual(rows[5][1], 2.493743e-01, accuracy: eps, "B@t=5")
        XCTAssertEqual(rows[5][2], 1.440950e-01, accuracy: eps, "C@t=5")

        // t=10
        XCTAssertEqual(rows[10][0], 3.678794e-01, accuracy: eps, "A@t=10")
        XCTAssertEqual(rows[10][1], 2.788478e-01, accuracy: eps, "B@t=10")
        XCTAssertEqual(rows[10][2], 3.532727e-01, accuracy: eps, "C@t=10")

        // t=20
        XCTAssertEqual(rows[20][0], 1.353353e-01, accuracy: eps, "A@t=20")
        XCTAssertEqual(rows[20][1], 2.415182e-01, accuracy: eps, "B@t=20")
        XCTAssertEqual(rows[20][2], 6.231465e-01, accuracy: eps, "C@t=20")

        // t=50
        XCTAssertEqual(rows[50][0], 6.737947e-03, accuracy: eps, "A@t=50")
        XCTAssertEqual(rows[50][1], 2.022440e-01, accuracy: eps, "B@t=50")
        XCTAssertEqual(rows[50][2], 7.910181e-01, accuracy: eps, "C@t=50")

        // conservation: A+B+C ≤ 1.0 at all times (no disposal, no decay)
        for (i, row) in rows.enumerated() {
            let total = row.reduce(0, +)
            XCTAssertEqual(total, 1.0, accuracy: 1e-4, "conservation at step \(i)")
        }
    }

    // MARK: - half-life = 5 days

    func testHalfLifeFiveDays() async {
        let rows = await run(halfLife: 5)
        let eps = 1e-5

        // t=0
        XCTAssertEqual(rows[0][0], 1.0,          accuracy: eps, "A@t=0")
        XCTAssertEqual(rows[0][1], 0.0,          accuracy: eps, "B@t=0")
        XCTAssertEqual(rows[0][2], 0.0,          accuracy: eps, "C@t=0")

        // t=1
        XCTAssertEqual(rows[1][0], 7.877067e-01, accuracy: eps, "A@t=1")
        XCTAssertEqual(rows[1][1], 7.508678e-02, accuracy: eps, "B@t=1")
        XCTAssertEqual(rows[1][2], 7.757064e-03, accuracy: eps, "C@t=1")

        // t=5
        XCTAssertEqual(rows[5][0], 3.032653e-01, accuracy: eps, "A@t=5")
        XCTAssertEqual(rows[5][1], 1.246872e-01, accuracy: eps, "B@t=5")
        XCTAssertEqual(rows[5][2], 7.204751e-02, accuracy: eps, "C@t=5")

        // t=10
        XCTAssertEqual(rows[10][0], 9.196986e-02, accuracy: eps, "A@t=10")
        XCTAssertEqual(rows[10][1], 6.971195e-02, accuracy: eps, "B@t=10")
        XCTAssertEqual(rows[10][2], 8.831819e-02, accuracy: eps, "C@t=10")

        // t=20
        XCTAssertEqual(rows[20][0], 8.458455e-03, accuracy: eps, "A@t=20")
        XCTAssertEqual(rows[20][1], 1.509489e-02, accuracy: eps, "B@t=20")
        XCTAssertEqual(rows[20][2], 3.894666e-02, accuracy: eps, "C@t=20")

        // t=50
        XCTAssertEqual(rows[50][0], 6.580026e-06, accuracy: eps, "A@t=50")
        XCTAssertEqual(rows[50][1], 1.975039e-04, accuracy: eps, "B@t=50")
        XCTAssertEqual(rows[50][2], 7.724786e-04, accuracy: eps, "C@t=50")

        // total activity decays: sum at t=50 should be much less than 1
        let total50 = rows[50].reduce(0, +)
        XCTAssertLessThan(total50, 0.01, "most activity should have decayed by t=50 (≈10 half-lives)")
    }
}
