import AppDomain
import FP
import Foundation

// MARK: - CSV

public let generateCalculatorCSV: @Sendable (CalculatorExportData) -> DeferredTask<Result<Data, Error>> = { input in
    DeferredTask {
        var lines: [String] = []

        // Header row
        let header = (["Time (\(input.lingo.timeUnit.label))"] + input.compartmentNames)
            .map { "\"\($0.replacingOccurrences(of: "\"", with: "\"\""))\"" }
            .joined(separator: ",")
        lines.append(header)

        // Data rows — full Double precision
        for row in input.rows {
            let timeStr = String(format: "%.6g", row.day)
            let values  = row.values.map { String(format: "%.9e", $0) }
            lines.append(([timeStr] + values).joined(separator: ","))
        }

        let csv  = lines.joined(separator: "\r\n")
        guard let data = csv.data(using: .utf8) else {
            return .failure(ExportError.encodingFailed)
        }
        return .success(data)
    }
}

// MARK: - PDF renderer

#if canImport(UIKit)
import UIKit

public let renderCalculatorPDF: @Sendable (CalculatorExportData) -> DeferredTask<Result<Data, Error>> = { input in
    DeferredTask {
        let a4 = CGRect(x: 0, y: 0, width: 595, height: 842)
        let renderer = UIGraphicsPDFRenderer(bounds: a4)
        let data = renderer.pdfData { ctx in
            ctx.beginPage()
            drawReportPage(input: input, bounds: a4)
        }
        return .success(data)
    }
}

private func drawReportPage(input: CalculatorExportData, bounds: CGRect) {
    let margin: CGFloat = 44
    let pageW = bounds.width - margin * 2
    var y: CGFloat = 42

    // ── Title ─────────────────────────────────────────────────────────────
    drawText(input.documentName,
             x: margin, y: &y,
             font: .systemFont(ofSize: 18, weight: .bold),
             color: .label)
    y += 4
    drawText("\(input.lingo.fieldName)  ·  \(input.compartmentNames.count) tracked compartments",
             x: margin, y: &y,
             font: .systemFont(ofSize: 10),
             color: .secondaryLabel)
    y += 14

    // ── Column layout ──────────────────────────────────────────────────────
    let colCount    = input.compartmentNames.count + 1   // time + n compartments
    let timeColW: CGFloat = 72
    let dataColW: CGFloat = max(60, (pageW - timeColW) / CGFloat(max(1, colCount - 1)))

    func xForCol(_ col: Int) -> CGFloat {
        col == 0 ? margin : margin + timeColW + CGFloat(col - 1) * dataColW
    }
    func colW(_ col: Int) -> CGFloat { col == 0 ? timeColW : dataColW }

    // Header
    let headerBg = UIColor.systemGray5
    headerBg.setFill()
    UIBezierPath(rect: CGRect(x: margin, y: y, width: pageW, height: 18)).fill()

    let headers = ["Time (\(input.lingo.timeUnit.label))"] + input.compartmentNames
    for (i, name) in headers.enumerated() {
        let truncated = name.count > 14 ? String(name.prefix(12)) + "…" : name
        drawTextInRect(truncated,
                       rect: CGRect(x: xForCol(i), y: y, width: colW(i), height: 18),
                       font: .systemFont(ofSize: 8, weight: .bold),
                       color: .label,
                       align: i == 0 ? .left : .right)
    }
    y += 20

    // Data rows
    let rowFont = UIFont.monospacedSystemFont(ofSize: 7.5, weight: .regular)
    let maxRows = Int((bounds.height - y - margin) / 12)
    let visibleRows = Array(input.rows.prefix(maxRows))

    for (ri, row) in visibleRows.enumerated() {
        if ri % 2 == 1 {
            UIColor.systemGray6.setFill()
            UIBezierPath(rect: CGRect(x: margin, y: y, width: pageW, height: 11)).fill()
        }
        let timeStr = String(format: "%.4g", row.day)
        drawTextInRect(timeStr,
                       rect: CGRect(x: xForCol(0), y: y, width: colW(0), height: 11),
                       font: rowFont, color: .label, align: .left)
        for (vi, val) in row.values.enumerated() {
            let valStr = String(format: "%.3e", val)
            drawTextInRect(valStr,
                           rect: CGRect(x: xForCol(vi + 1), y: y, width: colW(vi + 1), height: 11),
                           font: rowFont, color: .secondaryLabel, align: .right)
        }
        y += 12
    }

    if input.rows.count > maxRows {
        y += 6
        drawText("… \(input.rows.count - maxRows) more rows not shown",
                 x: margin, y: &y,
                 font: .italicSystemFont(ofSize: 8),
                 color: .secondaryLabel)
    }

    // Footer
    drawHRule(x: margin, y: bounds.height - 30, width: pageW)
    drawText("Generated by Biokinetics & Dosimetry",
             x: margin, y: bounds.height - 24,
             font: .systemFont(ofSize: 8),
             color: .secondaryLabel)
}

// MARK: - Drawing helpers

private func drawText(_ s: String, x: CGFloat, y: inout CGFloat,
                       font: UIFont, color: UIColor) {
    let attrs: [NSAttributedString.Key: Any] = [.font: font, .foregroundColor: color]
    s.draw(at: CGPoint(x: x, y: y), withAttributes: attrs)
    y += s.size(withAttributes: attrs).height + 2
}

private func drawText(_ s: String, x: CGFloat, y: CGFloat,
                       font: UIFont, color: UIColor) {
    let attrs: [NSAttributedString.Key: Any] = [.font: font, .foregroundColor: color]
    s.draw(at: CGPoint(x: x, y: y), withAttributes: attrs)
}

private func drawTextInRect(_ s: String, rect: CGRect, font: UIFont,
                              color: UIColor, align: NSTextAlignment) {
    let para = NSMutableParagraphStyle()
    para.alignment = align
    para.lineBreakMode = .byTruncatingTail
    s.draw(in: rect, withAttributes: [
        .font: font, .foregroundColor: color, .paragraphStyle: para
    ])
}

private func drawHRule(x: CGFloat, y: CGFloat, width: CGFloat) {
    UIColor.separator.setStroke()
    let p = UIBezierPath()
    p.move(to: CGPoint(x: x, y: y))
    p.addLine(to: CGPoint(x: x + width, y: y))
    p.lineWidth = 0.5
    p.stroke()
}

#else

public let renderCalculatorPDF: @Sendable (CalculatorExportData) -> DeferredTask<Result<Data, Error>> = { _ in
    DeferredTask { .failure(ExportError.pdfRequiresUIKit) }
}

#endif

// MARK: - Error

public enum ExportError: LocalizedError {
    case encodingFailed
    case pdfRequiresUIKit

    public var errorDescription: String? {
        switch self {
        case .encodingFailed:    "Could not encode data as UTF-8."
        case .pdfRequiresUIKit:  "PDF rendering requires UIKit (iOS/macOS)."
        }
    }
}
