#if canImport(CoreTransferable)
import Foundation

#if canImport(UIKit)
import UIKit

extension PDFExportInput {
    func generatePDF() throws -> Data {
        let a4 = CGRect(x: 0, y: 0, width: 595, height: 842)
        let renderer = UIGraphicsPDFRenderer(bounds: a4)
        return renderer.pdfData { ctx in
            ctx.beginPage()
            drawReportPage(bounds: a4)
        }
    }

    private func drawReportPage(bounds: CGRect) {
        let margin: CGFloat = 44
        let pageW = bounds.width - margin * 2
        var y: CGFloat = 42

        // Title
        drawText(documentName, x: margin, y: &y,
                 font: .systemFont(ofSize: 18, weight: .bold), color: .label)
        y += 4
        drawText("\(lingo.fieldName)  ·  \(compartmentNames.count) tracked compartments",
                 x: margin, y: &y, font: .systemFont(ofSize: 10), color: .secondaryLabel)
        y += 14

        // Column layout
        let timeColW: CGFloat = 72
        let dataColW: CGFloat = max(60, (pageW - timeColW) / CGFloat(max(1, compartmentNames.count)))
        func xForCol(_ col: Int) -> CGFloat { col == 0 ? margin : margin + timeColW + CGFloat(col - 1) * dataColW }
        func wForCol(_ col: Int) -> CGFloat { col == 0 ? timeColW : dataColW }

        // Header
        UIColor.systemGray5.setFill()
        UIBezierPath(rect: CGRect(x: margin, y: y, width: pageW, height: 18)).fill()
        let headers = ["Time (\(lingo.timeUnit.label))"] + compartmentNames
        for (i, name) in headers.enumerated() {
            let truncated = name.count > 14 ? String(name.prefix(12)) + "…" : name
            drawInRect(truncated, rect: CGRect(x: xForCol(i), y: y, width: wForCol(i), height: 18),
                       font: .systemFont(ofSize: 8, weight: .bold), color: .label,
                       align: i == 0 ? .left : .right)
        }
        y += 20

        let rowFont = UIFont.monospacedSystemFont(ofSize: 7.5, weight: .regular)
        let maxRows = Int((bounds.height - y - margin) / 12)
        for (ri, row) in rows.prefix(maxRows).enumerated() {
            if ri % 2 == 1 { UIColor.systemGray6.setFill(); UIBezierPath(rect: CGRect(x: margin, y: y, width: pageW, height: 11)).fill() }
            drawInRect(String(format: "%.4g", row.day),
                       rect: CGRect(x: xForCol(0), y: y, width: wForCol(0), height: 11),
                       font: rowFont, color: .label, align: .left)
            for (vi, val) in row.values.enumerated() {
                drawInRect(String(format: "%.3e", val),
                           rect: CGRect(x: xForCol(vi + 1), y: y, width: wForCol(vi + 1), height: 11),
                           font: rowFont, color: .secondaryLabel, align: .right)
            }
            y += 12
        }
        if rows.count > maxRows {
            y += 6
            let remaining = "… \(rows.count - maxRows) more rows not shown"
            remaining.draw(at: CGPoint(x: margin, y: y), withAttributes: [
                .font: UIFont.italicSystemFont(ofSize: 8), .foregroundColor: UIColor.secondaryLabel
            ])
        }

        // Footer
        UIColor.separator.setStroke()
        let rule = UIBezierPath(); rule.move(to: CGPoint(x: margin, y: bounds.height - 30))
        rule.addLine(to: CGPoint(x: bounds.width - margin, y: bounds.height - 30))
        rule.lineWidth = 0.5; rule.stroke()
        drawText("Generated by Biokinetics & Dosimetry",
                 x: margin, y: bounds.height - 24,
                 font: .systemFont(ofSize: 8), color: .secondaryLabel)
    }

    private func drawText(_ s: String, x: CGFloat, y: inout CGFloat, font: UIFont, color: UIColor) {
        let attrs: [NSAttributedString.Key: Any] = [.font: font, .foregroundColor: color]
        s.draw(at: CGPoint(x: x, y: y), withAttributes: attrs)
        y += s.size(withAttributes: attrs).height + 2
    }

    private func drawText(_ s: String, x: CGFloat, y: CGFloat, font: UIFont, color: UIColor) {
        s.draw(at: CGPoint(x: x, y: y), withAttributes: [.font: font, .foregroundColor: color])
    }

    private func drawInRect(_ s: String, rect: CGRect, font: UIFont, color: UIColor, align: NSTextAlignment) {
        let para = NSMutableParagraphStyle(); para.alignment = align; para.lineBreakMode = .byTruncatingTail
        s.draw(in: rect, withAttributes: [.font: font, .foregroundColor: color, .paragraphStyle: para])
    }
}

#else

extension PDFExportInput {
    func generatePDF() throws -> Data {
        throw CocoaError(.fileWriteUnknown)
    }
}

#endif
#endif
